--CLR FIX
--Run in master on SOURCE I nstance
USE master

GO

CREATE CERTIFICATE CLRTrustCert
ENCRYPTION BY PASSWORD=''
WITH SUBJECT='CLR ASSEMBLY TRUST CERT';
GO

CREATE LOGIN CLRTrustLogin FROM CERTIFICATE CLRTrustCert;
GO

GRANT UNSAFE ASSEMBLY TO CLRTrustLogin;
GO

BACKUP CERTIFICATE CLRTrustCert
TO FILE ''
WITH PRIVATE KEY(
FILE=